### ISSUE TITLE
Some Advice

### ISSUE THREAD

**Issue by jingyan-x** [doveccl/DOJ#29]
# Hello Dear Doveccl
I'm a student of zjy from hsez
I have some suggestions for DOJ
能不能把c++版本升级一下啊，特别是升级到c++17（~~这个很重要拜托了~~
另一点是对于搜索页面的保留功能
Thanks for your 辛苦运维 very much

**Comment by doveccl** [comment]
no more new features on branch v3, closed

**Comment by jingyan-x** [comment]
> no more new features on branch v3, closed



> no more new features on branch v3, closed

thank you very much
